### ISSUE TITLE
Green effect webcam from android device

### ISSUE THREAD

**Issue by tuannt591** [livekit/livekit-react#119] opened 2023-02-02 09:27 UTC
![Screenshot 2023-02-02 154321](https://user-images.githubusercontent.com/26372517/216275498-69eaa5e9-667b-47df-9fb4-c2e5ad741f12.jpg)

Hi. We are having a issue that when we make a call from android device (OnePlus mobile) and window PC, the android device's webcam displayed on window and linux chrome browsers displays a blueish tint as shown in the picture. Only on macos chrome does the video render correctly.

**Comment by lukasIO** [comment] 2023-02-06 09:39
closing as a duplicate of https://github.com/livekit/client-sdk-android/issues/176

**Closed by lukasIO** 2023-02-06 09:39 UTC

**Comment by davidliu** [comment] 2023-02-06 15:57
@tuannt591 did the macos chrome browser reliably render correctly? Could this have been a one-off success?

**Comment by daibo83** [comment] 2023-02-06 17:23
Replying in behalf of @tuannt591 as we both work on the same project: yes, all MacOs chrome browser do reliably render streams from android devices correctly.
