### ISSUE TITLE
Failed to parse source map: 'webpack:///dist/react-responsive.js' URL is not supported

### ISSUE THREAD

**Issue by git136975643** [livekit/livekit-react#84] opened 2022-08-24 09:15 UTC
yarn install
yarn start ，然后
```
livekit-react-example:start: WARNING in ../node_modules/react-responsive/dist/react-responsive.js
livekit-react-example:start: Module Warning (from ../node_modules/source-map-loader/dist/cjs.js):
livekit-react-example:start: Failed to parse source map: 'webpack:///dist/react-responsive.js' URL is not supported
livekit-react-example:start: 
livekit-react-example:start: webpack compiled with 1 warning
livekit-react-example:start: No issues found.
```
一直这样，不结束，也不出链接

**Comment by lukasIO** [comment] 2022-08-24 10:01
duplicate of https://github.com/livekit/livekit-react/issues/69

**Closed by lukasIO** 2022-08-24 10:01 UTC
